import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';

export default function Bookings({ history = false }) {
  const [bookings, setBookings] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = async () => { try { setLoading(true); const { data } = await api.get('/bookings/my'); setBookings(data.bookings); } catch (e) { setError(e.response?.data?.message || 'Unable to load bookings.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = history ? bookings.filter(b => ['Completed','Cancelled','Expired'].includes(b.status)) : bookings.filter(b => !['Completed','Cancelled','Expired'].includes(b.status));
  const cancel = async id => { if (!window.confirm('Cancel this booking?')) return; try { await api.put(`/bookings/${id}/cancel`); load(); } catch (e) { setError(e.response?.data?.message || 'Cancellation failed.'); } };
  return <section className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-wider text-cng-600">{history ? 'History' : 'Reservations'}</p><h1 className="mt-1 text-3xl font-extrabold">{history ? 'Booking history' : 'My bookings'}</h1><p className="mt-2 text-slate-500">{history ? 'Your completed and cancelled reservations.' : 'Manage your upcoming CNG refueling reservations.'}</p></div>{error && <div className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}{loading ? <div className="py-16 text-center text-slate-500">Loading bookings...</div> : visible.length === 0 ? <div className="card py-14 text-center"><h2 className="text-xl font-bold">No bookings here</h2><p className="mt-1 text-sm text-slate-500">{history ? 'Your booking history will appear here.' : 'Reserve a pump slot when you are ready.'}</p><Link to="/stations" className="mt-5 inline-flex rounded-xl bg-cng-600 px-5 py-3 text-sm font-bold text-white">Find a station</Link></div> : <div className="space-y-4">{visible.map(b => <article key={b._id} className="card"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="font-bold">{b.stationId?.name || 'CNG Station'}</h2><p className="mt-1 text-sm text-slate-500">{b.stationId?.address}</p><p className="mt-2 text-sm font-semibold">Booking ID: <span className="text-cng-700">{b.bookingId}</span></p></div><span className="h-fit rounded-full bg-cng-50 px-3 py-1.5 text-xs font-bold text-cng-700">{b.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Info label="Date" value={b.bookingDate}/><Info label="Time" value={`${b.startTime} – ${b.endTime}`}/><Info label="Pump" value={`Pump ${b.slotId?.slotNumber || '—'}`}/><Info label="Vehicle" value={b.vehicleNumber}/></div>{b.status === 'Confirmed' && <div className="mt-5 flex flex-col gap-4 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-slate-800">Booking QR code</p><p className="mt-1 text-xs text-slate-500">Show this QR code at the station for verification.</p></div>{b.qrCode && <img src={b.qrCode} alt={`QR code for booking ${b.bookingId}`} className="h-36 w-36 rounded-lg bg-white p-2" />}</div>}{b.status === 'Confirmed' && <button onClick={() => cancel(b.bookingId)} className="mt-1 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600 hover:bg-red-50">Cancel booking</button>}</article>)}</div>}</section>;
}
function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 font-bold text-slate-800">{value}</div></div>; }
