import { CalendarClock, CarFront, Clock3, Fuel, MapPin, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Dashboard() {
  const { user } = useAuth();
  const isAdmin = user.role !== 'user';
  const title = user.role === 'system_admin' ? 'System Administration' : user.role === 'station_admin' ? 'Station Administration' : 'Your CNG dashboard';
  return <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-3xl bg-gradient-to-r from-cng-700 to-cng-500 p-6 text-white shadow-lg sm:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-cng-100">{isAdmin ? 'CONTROL CENTER' : 'WELCOME BACK'}</p><h1 className="mt-1 text-3xl font-extrabold sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-cng-50">{isAdmin ? 'Manage your assigned operations from one place. Station and system management modules will connect here as the project grows.' : `Hello ${user.name}. Find a station, check availability and reserve your refueling slot.`}</p></div><div className="rounded-2xl bg-white/15 px-4 py-3 backdrop-blur"><div className="text-xs text-cng-100">Vehicle</div><div className="mt-1 flex items-center gap-2 font-bold"><CarFront size={18}/>{user.vehicleNumber}</div></div></div></div>{!isAdmin && <><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<MapPin/>} label="Nearby stations" value="—"/><Stat icon={<Fuel/>} label="Available slots" value="—"/><Stat icon={<Clock3/>} label="Avg. wait time" value="—"/><Stat icon={<CalendarClock/>} label="Upcoming booking" value="—"/></div><div className="mt-7 grid gap-5 md:grid-cols-3"><Action to="/stations" icon={<MapPin/>} title="Find CNG Stations" text="Explore nearby stations and live availability."/><Action to="/book-slot" icon={<CalendarClock/>} title="Book a Slot" text="Reserve a refueling time before you arrive."/><Action to="/bookings" icon={<Clock3/>} title="My Bookings" text="View upcoming and previous reservations."/></div></>}{isAdmin && <div className="mt-7 grid gap-5 md:grid-cols-2"><div className="card"><ShieldCheck className="text-cng-600"/><h2 className="mt-4 text-xl font-bold">Role-based access enabled</h2><p className="mt-2 text-sm leading-6 text-slate-500">You are signed in as <strong>{user.role === 'system_admin' ? 'System Admin' : 'Station Admin'}</strong>. Administrative modules will be added in the upcoming stages.</p></div><div className="card"><h2 className="text-xl font-bold">Account</h2><p className="mt-2 text-sm text-slate-500">Manage your profile and authentication details.</p><Link to="/profile" className="mt-5 inline-flex text-sm font-bold text-cng-600 hover:underline">Open profile →</Link></div></div>}</section>;
}
function Stat({icon,label,value}) { return <div className="card flex items-center gap-4"> <div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cng-50 text-cng-600">{icon}</div><div><div className="text-2xl font-extrabold">{value}</div><div className="text-sm text-slate-500">{label}</div></div></div>; }
function Action({to,icon,title,text}) { return <Link to={to} className="card group transition hover:-translate-y-1 hover:shadow-lg"><div className="grid h-11 w-11 place-items-center rounded-xl bg-cng-50 text-cng-600">{icon}</div><h2 className="mt-4 font-bold">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p><span className="mt-4 inline-block text-sm font-bold text-cng-600">Open →</span></Link>; }
