import { ArrowRight, CarFront, Clock3, Fuel, MapPin, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Home() {
  const { user } = useAuth();
  const primary = user ? '/dashboard' : '/register';
  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link to="/" className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cng-600 text-white"><CarFront size={21}/></span><div><div className="font-bold">Smart CNG</div><div className="text-[11px] text-slate-500">Tracking & Slot Management</div></div></Link><div className="flex items-center gap-2">{user ? <Link to="/dashboard" className="rounded-xl bg-cng-600 px-4 py-2.5 text-sm font-bold text-white">Dashboard</Link> : <><Link to="/login" className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100">Login</Link><Link to="/register" className="rounded-xl bg-cng-600 px-4 py-2.5 text-sm font-bold text-white">Get started</Link></>}</div></div></header>
    <main>
      <section className="bg-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-24 lg:px-8"><div><span className="inline-flex rounded-full bg-cng-50 px-3 py-1 text-xs font-extrabold uppercase tracking-wider text-cng-700">Smart refueling</span><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Find CNG Stations. Avoid Long Queues. Refuel Smarter.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-500">Locate nearby CNG stations, check real-time availability and reserve your refueling slot in advance.</p><div className="mt-8 flex flex-wrap gap-3"><Link to={user ? '/stations' : primary} className="inline-flex items-center gap-2 rounded-xl bg-cng-600 px-5 py-3.5 text-sm font-bold text-white hover:bg-cng-700">Find CNG Station <ArrowRight size={17}/></Link><Link to={user ? '/book-slot' : '/login'} className="rounded-xl border border-slate-200 px-5 py-3.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Book a Slot</Link></div></div><div className="rounded-3xl bg-gradient-to-br from-cng-50 via-white to-slate-100 p-6 shadow-sm"><div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-cng-600">Smart station view</p><h2 className="mt-1 text-xl font-extrabold">Know before you arrive</h2></div><Fuel className="text-cng-600"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Mini icon={<MapPin/>} title="Nearby stations" text="Compare stations by location and status."/><Mini icon={<Clock3/>} title="Live queue" text="See waiting vehicles and estimated time."/><Mini icon={<Fuel/>} title="Reserve a pump" text="Choose a date, time and available pump."/><Mini icon={<ShieldCheck/>} title="QR confirmation" text="Show your booking confirmation at the station."/></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="text-center"><p className="text-sm font-bold uppercase tracking-wider text-cng-600">How it works</p><h2 className="mt-2 text-3xl font-extrabold">Three simple steps</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Step n="01" title="Find a station" text="Search CNG stations and compare availability, queue length, price and distance."/><Step n="02" title="Reserve your slot" text="Pick a date, time and available pump. Your booking gets a unique ID and QR code."/><Step n="03" title="Arrive and refuel" text="Show your confirmation, join the managed flow and get refueled with less waiting."/></div></section>
      <section className="bg-slate-900 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 md:grid-cols-3 lg:px-8"><Benefit icon={<Clock3/>} title="Less waiting" text="Use live queue information and advance reservations to plan your visit."/><Benefit icon={<MapPin/>} title="Better discovery" text="Find nearby stations with map-based location and operational status."/><Benefit icon={<ShieldCheck/>} title="Controlled operations" text="Station and system admins get role-based tools for bookings and queues."/></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-6 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} Smart CNG Tracking & Slot Management System</span><span>College final-year project</span></div></footer>
  </div>;
}
function Mini({icon,title,text}){return <div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-cng-600">{icon}<span className="font-bold text-slate-800">{title}</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
function Step({n,title,text}){return <div className="card"><span className="text-sm font-black text-cng-600">{n}</span><h3 className="mt-3 text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
function Benefit({icon,title,text}){return <div><div className="flex items-center gap-3 text-cng-400">{icon}<h3 className="font-extrabold text-white">{title}</h3></div><p className="mt-3 text-sm leading-6 text-slate-300">{text}</p></div>}
