import { useEffect, useState } from 'react';
import { CarFront, LockKeyhole, Mail, Phone, Save, UserRound } from 'lucide-react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function Profile() {
  const { user } = useAuth();
  const [form, setForm] = useState({name:'',phone:'',vehicleNumber:'',vehicleType:'',password:''});
  const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{ if(user) setForm({name:user.name,phone:user.phone,vehicleNumber:user.vehicleNumber,vehicleType:user.vehicleType,password:''}); },[user]);
  const update=(k,v)=>setForm({...form,[k]:v});
  const submit=async(e)=>{e.preventDefault();setError('');setMessage('');try{setLoading(true);const {data}=await api.put('/users/profile',form);localStorage.setItem('smart_cng_user',JSON.stringify(data.user));setMessage('Profile updated successfully.');}catch(err){setError(err.response?.data?.message||'Could not update profile.');}finally{setLoading(false)}};
  return <section className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-wider text-cng-600">Account</p><h1 className="mt-1 text-3xl font-extrabold">Profile settings</h1><p className="mt-2 text-slate-500">Keep your contact and vehicle details up to date.</p></div><div className="card"><div className="mb-6 flex items-center gap-4 border-b border-slate-100 pb-6"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-cng-50 text-cng-600"><UserRound/></div><div><h2 className="font-bold">{user.name}</h2><p className="text-sm text-slate-500">{user.role.replace('_',' ')}</p></div></div><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2">{message&&<div className="sm:col-span-2 rounded-xl bg-cng-50 px-4 py-3 text-sm font-semibold text-cng-700">{message}</div>}{error&&<div className="sm:col-span-2 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}<Field label="Name" icon={<UserRound size={17}/>} value={form.name} onChange={v=>update('name',v)}/><Field label="Email" icon={<Mail size={17}/>} value={user.email} disabled/><Field label="Phone" icon={<Phone size={17}/>} value={form.phone} onChange={v=>update('phone',v)}/><Field label="Vehicle number" icon={<CarFront size={17}/>} value={form.vehicleNumber} onChange={v=>update('vehicleNumber',v)}/><label><span className="mb-2 block text-sm font-semibold text-slate-700">Vehicle type</span><select value={form.vehicleType} onChange={e=>update('vehicleType',e.target.value)} className="input"><option>Car</option><option>Auto Rickshaw</option><option>Taxi</option><option>Bus</option><option>Truck</option><option>Other</option></select></label><Field label="New password (optional)" icon={<LockKeyhole size={17}/>} type="password" value={form.password} onChange={v=>update('password',v)} placeholder="Leave blank to keep current"/><button disabled={loading} className="primary-btn sm:col-span-2"><Save size={17}/>{loading?'Saving...':'Save changes'}</button></form></div></section>;
}
function Field({label,icon,type='text',value,onChange,placeholder,disabled=false}){return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><div className="relative">{icon&&<span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">{icon}</span>}<input type={type} value={value} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder} disabled={disabled} className={`input pl-10 ${disabled?'bg-slate-50 text-slate-400':''}`}/></div></label>}
