import { useEffect, useState } from 'react';
import { Clock3, Fuel, MapPin, Navigation, Search } from 'lucide-react';
import api from '../services/api';

export default function Stations() {
  const [stations, setStations] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { try { setLoading(true); setError(''); const params={}; if(search.trim()) params.search=search.trim(); if(status!=='All') params.status=status; const {data}=await api.get('/stations',{params}); setStations(data.stations); } catch(err){setError(err.response?.data?.message||'Unable to load stations.');} finally{setLoading(false);} };
  useEffect(()=>{const timer=setTimeout(load,300);return()=>clearTimeout(timer)},[search,status]);
  return <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-wider text-cng-600">Stations</p><h1 className="mt-1 text-3xl font-extrabold">Find CNG stations</h1><p className="mt-2 text-slate-500">Search stations and compare availability before you travel.</p></div><div className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by station name or area..." className="input pl-10"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="input sm:w-44"><option>All</option><option>Available</option><option>Open</option><option>Busy</option><option>Closed</option></select></div>{error&&<div className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}{loading?<div className="py-16 text-center text-slate-500">Loading stations...</div>:stations.length===0?<div className="card py-16 text-center"><Fuel className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 font-bold">No stations found</h2><p className="mt-1 text-sm text-slate-500">Try a different station name or status.</p></div>:<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{stations.map(station=><StationCard key={station._id} station={station}/>)}</div>}</section>;
}
function StationCard({station}){const wait=station.queueLength*station.averageServiceMinutes;return <article className="card flex flex-col"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cng-50 text-cng-600"><Fuel size={21}/></div><div><h2 className="font-bold leading-5">{station.name}</h2><div className="mt-1 flex items-start gap-1 text-xs text-slate-500"><MapPin size={14} className="mt-0.5 shrink-0"/>{station.address}</div></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${station.status==='Busy'?'bg-amber-50 text-amber-700':station.status==='Closed'?'bg-red-50 text-red-700':'bg-cng-50 text-cng-700'}`}>{station.status}</span></div><div className="mt-5 grid grid-cols-2 gap-2"><Metric label="Available slots" value={`${station.availableSlots}/${station.totalSlots}`}/><Metric label="Queue" value={`${station.queueLength} vehicles`}/><Metric label="Est. wait" value={`${wait} min`} icon={<Clock3 size={14}/>}/><Metric label="CNG price" value={`₹${station.cngPrice}/kg`}/></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4 text-xs text-slate-500"><span>{station.openingTime}–{station.closingTime}</span>{station.distanceKm!==null&&<span>{station.distanceKm} km away</span>}</div><div className="mt-4 grid grid-cols-2 gap-2"><button disabled className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-400">View Details</button><button disabled className="flex items-center justify-center gap-1 rounded-xl bg-cng-600 px-3 py-2.5 text-sm font-bold text-white opacity-50"><Navigation size={15}/> Book Slot</button></div></article>}
function Metric({label,value,icon}){return <div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-1 text-[11px] font-semibold text-slate-400">{icon}{label}</div><div className="mt-1 font-bold text-slate-800">{value}</div></div>}
